### ISSUE TITLE
EnvironmentError: pkg-config is not installed

### ISSUE THREAD

**Issue by ds7711** [PaulEcoffet/birdsonganalysis#1]
Hi, I am trying to install birdsonganalysis using Anaconda (python 2.7.14) on Windows 10. I have installed "pkgconfig" but it constantly gives me the error "EnvironmentError: pkg-config is not installed". Any help/suggestions will be appreciated. Thanks a lot. 

Best,
Ming

**Comment by NickleDave** [comment]
Hey @ds7711 can you post the full traceback you're getting?
I seem to remember getting this error at some point but I don't quite remember what I did to fix it.
I have `birdsonganalysis` installed on Ubuntu 14 with Anaconda and have been able to run it, I'm attaching my spec-file.txt in case it helps.
[spec-file.txt](https://github.com/PaulEcoffet/birdsonganalysis/files/1843389/spec-file.txt)
You can use this file like so:
`$ conda create --name birdsonganalysis --file spec-file.txt`
(see https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)

Hope that helps
--David

**Comment by ds7711** [comment]
Thanks for the quick reply. I will try your method on my laptop with Ubuntu during the weekend. I copied the error message. Hopefully, it is informative......
"""
  File "c:\users\md\appdata\local\temp\easy_install-6bbnnz\libtfr-2.1.2\setup.py", line 101, in <module>

  File "C:\Anaconda2\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Anaconda2\lib\site-packages\setuptools\command\bdist_egg.py", line 169, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Anaconda2\lib\site-packages\setuptools\command\bdist_egg.py", line 155, in call_command
    self.run_command(cmdname)
  File "C:\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Anaconda2\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Anaconda2\lib\distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "C:\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Anaconda2\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "C:\Anaconda2\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "c:\users\md\appdata\local\temp\easy_install-6bbnnz\libtfr-2.1.2\setup.py", line 64, in build_extensions

  File "C:\Anaconda2\lib\site-packages\pkgconfig\pkgconfig.py", line 221, in parse
    return parse_package(packages)
  File "C:\Anaconda2\lib\site-packages\pkgconfig\pkgconfig.py", line 195, in parse_package
    out = _query(package, '--cflags --libs')
  File "C:\Anaconda2\lib\site-packages\pkgconfig\pkgconfig.py", line 62, in _wrapper
    raise EnvironmentError("pkg-config is not installed")
EnvironmentError: pkg-config is not installed
"""

**Comment by NickleDave** [comment]
Ah okay, I think I remember what I did now.

Instead of running `setup.py`, I just set up a conda environment like so:
```bash
$ conda create -n birdsonganalysis python=3.6 numpy scipy matplotlib seaborn
$ source activate birdsonganalysis
(birdsonganalysis) $ pip install libtfr
```

At least, `conda list` shows that `libtfr` was installed with `pip`.

If I remember right, there's a couple of `print` statements you'll have to convert to function calls but besides that I think most of the code works with Python 3.

Btw, we have a Google groups for songbird-related code if you want to join:
https://groups.google.com/forum/#!forum/songbird-code

--David

**Comment by PaulEcoffet** [comment]
Hi, I am the developer of birdsonganalysis. I created this package last year during an internship. As I was the only user, I didn't do a lot of effort making it easy to install or heavily portable.

I think the main problem you have is that Birdsonganalysis is built for python 3.4 and more. It might work with python 2 but I have never tested it and I will never make it compatible with python 2.7 as it may be too much work and python 2.7 will be obsolete in 2020 (https://pythonclock.org/).

I am really glad to learn that people are actually using my package! I can improve the documentation a bit and make installation a bit more easy I think. I am no longer working on bird songs though, so I will not add any new features.

I am also not really confident in the results given by the library. Even though the extraction of features seems correct, similarity computation is most likely buggy. The computation of similarity is rather complex and I had trouble understanding all the steps of similarity computation in "A procedure for an automated measurement of song similarity", in SAP2011 source code or in matlab SAT.

The code of the package is rather simple and rather well written and documented. If you feel like testing its results or make some improvements, I will gladly update the code. Feel free to ask if you have any questions!

**Comment by NickleDave** [comment]
Hey Paul, thank you for putting the package together. It is great. And thank you for using modern and not legacy Python 😏

I think you might not be the only one who has had trouble understanding "A procedure..." 😂
I saw in the docstrings/comments where you said you weren't sure about some of the implementation details. Any chance you could make Issues out of them on this repo for people to work on? I had definitely thought about contributing.

I know Ofer and Dina have talked about transitioning to Python at some point to make SAP easier to maintain--I actually talked with them about it November. Maybe your package could be a starting point. We could get Ofer's feedback on the things you weren't sure about. And I know other people would be interested in such an implementation as well. There's a lot of nice things about SAP but it's kind of a pain point to only be able to run it on Windows.

**Comment by PaulEcoffet** [comment]
I will open a few issues. For me, the main thing to do is to write unit tests to assert that the code behaves as expected by the song bird research community. There are a few unit tests already written but they are pretty useless. I lacked a standard implementation of the birdsong measurements to compare my results, most notably because I didn't trust SAT and working with SAP was rather complicated for me as it was Windows only.

**Comment by NickleDave** [comment]
Understood.

In terms of testing whether the library produces the same results as SAP:
I could run SAP on some of the repos of song that are available, such as:
https://datadryad.org//resource/doi:10.5061/dryad.7137r
and then the output could be used as an "oracle" which the tests would be run against.
I could put the SQL output in a Figshare repo and then write a Python script to download it so it wouldn't have to be part of the library.
This library has some code for getting data out of the SAP SQL database:
https://github.com/soderstromk/KLFromRecordingDays
so that might be a place to start

**Comment by ds7711** [comment]
Sorry for the late reply. Thanks for providing details about the issue and I will try it with Python 3. I would also like to contribute if anyone is thinking to improve `birdsonganalysis`.  I will extract features from some zebra finch songs using SAP and share these songs and results as a basis for testing if anyone needs it.
